export const store = [
  {
    title: "adidas max air",
    price: "150,000",
    img: "images/five.png",
    weight: "0.5",
    qty: "2",
    color: "blue",
    customer: "Unuefe Ejoke, 08064491812",
    vendor: "Shimus Clothing and Accessories",
    address: "2, Sonola Street, Aguda-Ogba",
    orderStatus: ["pending, delivered"],
    orderDate: "June 12, 2022",
    deliveryDate: "June 14, 2022",
  },
  {
    title: "Modern Wrist watch",
    price: "120,000",
    img: "images/four.png",
    weight: "0.8",
    qty: "2",
    color: "blue",
    customer: "Unuefe Ejoke, 08064491812",
    vendor: "Shimus Clothing and Accessories",
    address: "2, Sonola Street, Aguda-Ogba",
    orderStatus: ["pending, delivered"],
    orderDate: "June 12, 2022",
    deliveryDate: "June 14, 2022",
  },
  {
    title: "iphone 12",
    price: "350,000",
    img: "images/three.png",
    weight: "0.5",
    qty: "2",
    color: "black",
    customer: "Unuefe Ejoke, 08064491812",
    vendor: "Shimus Clothing and Accessories",
    address: "2, Sonola Street, Aguda-Ogba",
    orderStatus: ["pending, delivered"],
    orderDate: "June 12, 2022",
    deliveryDate: "June 14, 2022",
  },
  {
    title: "Nike Airforce",
    price: "24,000",
    img: "images/two.png",
    weight: "0.5",
    qty: "2",
    color: "blue",
    customer: "Unuefe Ejoke, 08064491812",
    vendor: "Shimus Clothing and Accessories",
    address: "2, Sonola Street, Aguda-Ogba",
    orderStatus: ["pending, delivered"],
    orderDate: "June 12, 2022",
    deliveryDate: "June 14, 2022",
  },
  {
    title: "T-Shirt",
    price: "5,000",
    img: "images/one.png",
    weight: "0.5",
    qty: "2",
    color: "blue",
    customer: "Unuefe Ejoke, 08064491812",
    vendor: "Shimus Clothing and Accessories",
    address: "2, Sonola Street, Aguda-Ogba",
    orderStatus: ["pending, delivered"],
    orderDate: "June 12, 2022",
    deliveryDate: "June 14, 2022",
  },
  {
    title: "MacBook Air 2020",
    price: "900,000",
    img: "images/six.png",
    weight: "0.5",
    qty: "2",
    color: "blue",
    customer: "Unuefe Ejoke, 08064491812",
    vendor: "Shimus Clothing and Accessories",
    address: "2, Sonola Street, Aguda-Ogba",
    orderStatus: ["pending, delivered"],
    orderDate: "June 12, 2022",
    deliveryDate: "June 14, 2022",
  },
];
